#!/usr/bin/env python3
"""Render per-cell paired-stats rows as LaTeX for Supplementary Table~S11.

Usage:
    python3 scripts/emit_paired_stats_latex.py \
        outputs/v4_exp_chestxdet10/paired_stats.parquet
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

PRETTY_MODEL = {
    "raddino": "RAD-DINO",
    "dinov2": "DINOv2-B/14",
    "dinov3": "DINOv3 ViT-7B",
    "biomedclip": "BiomedCLIP",
    "medsiglip": "MedSigLIP",
}
MODEL_ORDER = ["raddino", "dinov2", "dinov3", "biomedclip", "medsiglip"]
CLASS_ORDER = ["Calcification", "Nodule", "Mass"]


def fmt_p(p: float) -> str:
    if p < 1e-4:
        return r"$<10^{-4}$"
    if p < 1e-3:
        return f"${p:.4f}$"
    return f"${p:.3f}$"


def fmt_q(q: float) -> str:
    if q < 1e-4:
        return r"$<10^{-4}$"
    if q < 1e-3:
        return f"${q:.4f}$"
    return f"${q:.3f}$"


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    p = Path(sys.argv[1])
    df = pd.read_parquet(p)
    df["model_order"] = df["model"].map(MODEL_ORDER.index)
    df["class_order"] = df["class"].map(CLASS_ORDER.index)
    df = df.sort_values(["model_order", "class_order"])

    print("% Auto-generated by scripts/emit_paired_stats_latex.py from")
    print(f"% {p}")
    n_cells = len(df)
    n_rejected = int(df["rejected_q05"].sum())
    print(f"% Cells: {n_cells}; rejected at BH-FDR q≤0.05: {n_rejected}/{n_cells}")
    print(f"% Δ range: [{df['delta'].min():+.3f}, {df['delta'].max():+.3f}]")
    print()
    last_model = None
    for _, r in df.iterrows():
        if last_model is None or r["model"] != last_model:
            if last_model is not None:
                print(r"\midrule")
            print(rf"\multirow{{3}}{{*}}{{{PRETTY_MODEL[r['model']]}}}")
            last_model = r["model"]
        print(
            f" & {r['class']:<14}"
            f" & ${r['auc_cls']:.3f}$"
            f" & ${r['auc_patch_local']:.3f}$"
            f" & ${r['delta']:+.3f}$"
            f" & $[{r['delta_ci_lo']:+.3f},\\,{r['delta_ci_hi']:+.3f}]$"
            f" & {fmt_p(r['p_paired_bootstrap'])}"
            f" & {fmt_q(r['q_bh'])}"
            f" & {int(r['n_test'])} \\\\"
        )

    print()
    delta_min = df["delta"].min()
    delta_max = df["delta"].max()
    p_max = df["p_paired_bootstrap"].max()
    q_max = df["q_bh"].max()
    print("% Headline summary (drop into \\PairedHeadline):")
    if n_rejected == n_cells:
        thresh = "10^{-4}" if p_max < 1e-4 else f"{p_max:.4f}"
        print(
            f"% All {n_cells} cells reject the null at BH-FDR q ≤ 0.05 "
            f"(max raw p = {thresh}; max q = {q_max:.4f}); "
            f"per-cell Δ ranges {delta_min:+.3f} to {delta_max:+.3f}."
        )
    else:
        print(
            f"% {n_rejected} of {n_cells} cells reject at BH-FDR q ≤ 0.05; "
            f"max q = {q_max:.4f}."
        )


if __name__ == "__main__":
    main()
